# Generated by Django 4.0.4 on 2022-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('sku', models.PositiveIntegerField()),
                ('precion', models.PositiveIntegerField()),
            ],
        ),
    ]
